#' Download ERA5 data from the Copernicus Climate Data Store (CDS) API in R
#'
#' This function allows users to download ERA5 data from the Copernicus Climate Data Store (CDS) API in R. \cr
#' The function uses the ecmwf package to access the CDS API and downloads the data in the NetCDF format. \cr
#' It will return the downloaded data as a SpatRaster object cropped to the extent of your aoi and can be used for further analysis. \cr
#' It simplifies the downloading of ERA5 datasets by summarizing the necessary steps to access the CDS API and providing filtering options . \cr
#'
#'
#' @param user Character string. Your Copernicus Climate Data Store (CDS) API username
#' @param key Character string. Your Copernicus Climate Data Store (CDS) API key
#' @param dataset_short_name Character string.. The short name of the ERA5 dataset to download.
#' @param variable Character string. The variable to download from the ERA5 dataset.
#' @param StartDate A character string or Date object specifying the start date of the data extraction in the format "YYYY-MM-DD" (e.g. "2010-01-01").
#' @param EndDate A character string or Date object specifying the end date of the data extraction in the format "YYYY-MM-DD" (e.g. "2018-11-05").
#' @param year_interval An integer specifying the interval for the years (e.g. 2,3,...). The default is 1 (optional parameter).
#' @param month_interval An integer specifying the interval for the months (e.g. 2,3,...). The default is 1 (optional parameter).
#' @param day_interval An integer specifying the interval for the days (e.g. 2,3,...). The default is 1 (optional parameter).
#' @param target_years A character vector specifying the years to be selected (e.g. c("2015", "2016", "2017")). If provided, only these years will be selected and the months and days adjusted (optional parameter).
#' @param target_months A character vector specifying the months to be selected (e.g. c("01", "02", "03")). If provided, only these months will be selected and the days and years adjusted (optional parameter).
#' @param target_days A character vector specifying the days to be selected (e.g. c("15", "16", "17")). If provided, only these days will be selected and the months and years adjusted (optional parameter).\cr
#' @param season A character string specifying the season to be selected (e.g. "DJF", "MAM", "JJA", "SON") (optional parameter) \cr
#' @param aoi The Area of interest (aoi) specified by the user. It can be any object of the sf or terra package.\cr
#' The function will automatically determine the extent of the aoi and round it to the grid resolution of the dataset. \cr
#' Instead, the user can also select coordinates in the format c(North/ West/South/East, e.g. 50.75/9/47.5/14).
#' @param country_name A character string specifying the name of the country to be selected as provided by the 'rgeoboundaries' package.\cr
#' This is an optional parameter and can be used instead of the aoi parameter.
#' @param admin_level An integer specifying the administrative level of the country to be selected. Optional parameter than can be combined with the country_name parameter.
#' @param product_type A character string specifying the product type of the dataset. Some datasets require a product type to be specified (optional parameter).
#' @param pressure_level A character string specifying the pressure level to be selected. This parameter is only relevant for pressure datasets (optional parameter).
#' @param target_file A character string specifying the name of the target file to store the downloaded data. \cr
#' If not provided, a default file name will be generated by oncatenating the variable name, StartDate and EndDate (optional parameter).
#' @param all_hours Logical. If TRUE, the function will download all hours of the day. If FALSE, the function will download only the time specified in the 'time' parameter. Default is FALSE (optional parameter).
#' @param time_out A character string specifying the time out for the download in hours or seconds. The default is 1 hour (optional parameter).
#' @param path A character string specifying the path to store the downloaded data. If not provided, the data will be stored in the current working directory (optional parameter).
#' @param time A character string or list of character strings specifying the time of the day to download the data (e.g.time <-sprintf("%02d:00", 2:8)   \cr.
#' For monthly averaged datasets, the time is automatically set to '00:00'.
#' @param grid A character string specifying the grid resolution of the dataset. The default is ".5/.5" for ERA5 datasets and ".1/.1" for ERA5 land datasets (optional parameter).
#' @import ecmwfr
#' @import terra
#' @import sf
#' @import rgeoboundaries
#'
#' @return A SpatRaster object containing the downloaded ERA5 data cropped to the extent of the aoi.
#'
#' @export
#'
get_era5 <- function(user, key, dataset_short_name, variable, StartDate, EndDate, time, aoi = NULL, time_out = NULL,
                     year_interval = NULL, month_interval = NULL, day_interval = NULL, target_years = NULL,
                     target_months = NULL, target_days = NULL, season = NULL, country_name = NULL,
                     admin_level = NULL, pressure_level = NULL, target_file = NULL, all_hours = FALSE,
                     path = NULL, product_type = NULL, grid = NULL) {

  # If not provided, set default values for optional parameters
  if (missing(year_interval)) year_interval <- 1
  if (missing(month_interval)) month_interval <- 1
  if (missing(day_interval)) day_interval <- 1
  if (missing(aoi)) aoi <- NULL
  if (missing(target_years)) target_years <- NULL
  if (missing(target_months)) target_months <- NULL
  if (missing(target_days)) target_days <- NULL
  if (missing(season)) season <- NULL
  if (missing(country_name)) country_name <- NULL
  if (missing(admin_level)) admin_level <- NULL
  if (missing(pressure_level)) pressure_level <- NULL
  if (missing(target_file)) target_file <- NULL
  if (missing(all_hours)) all_hours <- FALSE
  if (missing(time_out)) time_out <- "1h"
  if (missing(path)) path <- NULL
  if (missing(product_type)) product_type <- NULL
  if (missing(grid)) grid <- NULL

  # Set default grid value for ERA5 land and ERA5 datasets
  # ERA5 land has a grid of 0.1/0.1
  # ERA5 datasets have a grid of 0.5/0.5
  if (is.null(grid)) {
    if (grepl("land", dataset_short_name, ignore.case = TRUE)) {
      grid <- ".1/.1"
    } else {
      grid <- ".5/.5"
    }
  }

  # Set the key for the user to access the Copernicus API
  # function from the ecmwf package
  wf_set_key(
    user = user,
    key = key,
    service = "cds"
  )
  # Pressure level can only be selected when a pressure dataset is selected
  # Check if pressure_level is selected and dataset_short_name contains 'pressure'
  if (!is.null(pressure_level) && !grepl("pressure", dataset_short_name, ignore.case = TRUE)) {
    stop("Pressure level can only be selected when a pressure dataset is selected.")
  }
  # Time is automatically set to '00:00' for monthly averaged datasets
  # as the time is not relevant for these datasets
  # Default setting by the API
  if (dataset_short_name %in% c("reanalysis-era5-single-levels-monthly-means",
                                "reanalysis-era5-pressure-levels-monthly-means",
                                "reanalysis-era5-land-monthly-means") &&
      (!is.null(product_type) &&
       product_type %in% c("monthly_averaged_reanalysis", "monthly_averaged_ensemble_members"))) {
    time <- "00:00"
    warning("Time is automatically set to '00:00' for monthly averaged datasets.")
  }

  # If a country name is provided, use the selected country as aoi
  if (is.null(aoi) && !is.null(country_name)) {
    aoi <- generate_spatial_obj(country_name, admin_level)
  }
  # if no aoi and no country name are provided, stop the function
  if (is.null(aoi)) {
    stop("Please provide an Area of Interest (aoi) or a country name.")
  }

  # Determine target months based on seasonal data if specified
  if (!is.null(season)) {
    target_months <- MCERA5::get_seasonal_data(season)
  }
  # extract date components to make them in the right format for the API
  # API needs years, months and days as separate lists
  # the extract_date_components function provides various options to filter the dates
  date_components <- MCERA5::extract_date_components(
    StartDate = StartDate,
    EndDate = EndDate,
    dataset_short_name = dataset_short_name,
    year_interval = year_interval,
    month_interval = month_interval,
    day_interval = day_interval,
    target_years = target_years,
    target_days = target_days,
    target_months = target_months,
  )
  # Extract the extent of the aoi in the format N/W/S/E as required by the API
  # The extent is rounded to the grid resolution so that the coordinates align with the grid
  extent_string <- MCERA5::get_extent_rounded_2_grid(aoi, grid)

  # Generate default target file name if not provided
  if (is.null(target_file)) {
    target_file <- MCERA5::generate_default_target_file_name(variable, StartDate, EndDate)
  }
  # add a variable for time that downloades all hours
  if ("all_hours" == TRUE) {
    time <- sprintf("%02d:00", 0:23)
  }
  # Define the request parameters for the Copernicus API
  request <- list(
    "dataset_short_name" = dataset_short_name,
    "product_type"       = product_type,
    "variable"           = variable,
    'pressure_level'     = pressure_level,
    "year"               = date_components$year,
    "month"              = date_components$month,
    "day"                = date_components$day,
    "time"               = time,
    "grid"               = grid,
    "area"               = extent_string, #N/W/S/E format
    "format"             = "netcdf",
    "target"             = target_file
  )
  # Determine the target directory to store the ncfile (by default, the current working directory)
  if (is.null(path)) {
    target_path <- getwd()  # Use the current working directory if no path is provided
  } else {
    target_path <- path  # Use the provided path
  }
  # add timeout in hours or seconds
  time_out <- MCERA5::convert_hours_to_seconds(time_out)

  # Execute the request and download the ncfile
  ncfile <- wf_request(
    user = user,
    request = request,
    transfer = TRUE,
    verbose = TRUE,
    time_out = time_out,
    path = target_path
  )
  # Check if the download was successful
  if (!is.null(ncfile)) {
    message("You successfully downloaded the variable ", variable, " from the dataset ", dataset_short_name, " for the time period ", StartDate, " to ", EndDate," as SpatRaster. Use print to inspect the SpatRaster object.")
  } else {
    warning("There was an issue with the download. Please check your parameters and try again.")
  }

  # Rasterize the downloaded netCDF file and mask it to the aoi
  masked_raster <- MCERA5::rasterize_and_mask(ncfile, aoi)

  # remove the time values that are outside of StartDate or EndDate
  # This is necessary when selecting target_months or a season
  # as the API will return all the selected months for a year even if it includes only one month
  # e.g. if StartDate is 2016-12-01 and target_months is 12 and 05, it will return both months for 2016
  raster_times <- time(masked_raster)
  valid_times <- list()

  for (i in seq_along(raster_times)) {
    if (as.Date(raster_times[i]) >= as.Date(StartDate) && as.Date(raster_times[i]) <= as.Date(EndDate)) {
      valid_times[[length(valid_times) + 1]] <- i
    }
  }
  # Subset the masked raster to include only valid time steps
  masked_raster <- masked_raster[[unlist(valid_times)]]
  # Return the masked raster
  return(masked_raster)
}
